---
- name: Link the .zshrc
  file:
    src: "{{ role_path }}/files/dot_zshrc.zsh"
    dest: ~/.zshrc
    state: link

- name: Link the .antigenrc
  file:
    src: "{{ role_path }}/files/dot_antigenrc.zsh"
    dest: ~/.antigenrc
    state: link

- name: Link the .pk10
  file:
    src: "{{ role_path }}/files/dot_p10k.zsh"
    dest: ~/.p10k.zsh
    state: link

- name: Ensure ~/.zshd directory exists
  file:
    dest: ~/.zshd
    state: directory

- name: Link the additional .zshd/ files
  file:
    src: "{{ role_path }}/files/dot_zshd/{{ item }}"
    dest: "~/.zshd/{{ item }}"
    state: link
  loop:
    - aliases.zsh
    - completions.zsh
    - functions.zsh
    - variables.zsh

- name: Change user shell to ZSH
  tags: essential
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
