MAKEFLAGS="--jobs=$(nproc)"
RUSTFLAGS="-C opt-level=2 -C target-cpu=native"
LDFLAGS="-fuse-ld=mold"
RUSTFLAGS="-C link-arg=-fuse-ld=mold"
COMPRESSZST=(zstd -c -T0 --auto-threads=logical -)
COMPRESSGZ=(pigz -c -f -n)
COMPRESSBZ2=(lbzip2 -c -f)
COMPRESSLZ=(plzip -c -f)
