access.rules = [
  {
    matches = [
      {
        application.process.binary = "vivaldi-bin"
      }
    ]
    actions = {
      update-props = {
        default_permissions = "rx"
      }
    }
  }
  {
    matches = [
      {
        application.process.binary = "thorium"
      }
    ]
    actions = {
      update-props = {
        default_permissions = "rx"
      }
    }
  }
  {
    matches = [
      {
        application.process.binary = "brave"
      }
    ]
    actions = {
      update-props = {
        default_permissions = "rx"
      }
    }
  }
  {
    matches = [
      {
        application.process.binary = "helium"
      }
    ]
    actions = {
      update-props = {
        default_permissions = "rx"
      }
    }
  }
  {
    matches = [
      {
        application.process.binary = "zen"
      }
    ]
    actions = {
      update-props = {
        default_permissions = "rx"
      }
    }
  }
  {
    matches = [
      {
        application.process.binary = "electron"
      }
    ]
    actions = {
      update-props = {
        default_permissions = "rx"
      }
    }
  }
]
