source /home/ton/.config/nushell/modules/aliases.nu
source /home/ton/.config/nushell/modules/completions.nu
source /home/ton/.config/nushell/modules/random.nu
source /home/ton/.config/nushell/modules/tools.nu
source /home/ton/.config/nushell/modules/utilities.nu
source /home/ton/.config/nushell/externals/aws.nu
source /home/ton/.config/nushell/externals/azure.nu
source /home/ton/.config/nushell/externals/dotnet.nu
source /home/ton/.config/nushell/externals/git.nu
source /home/ton/.config/nushell/externals/jc.nu
source /home/ton/.config/nushell/externals/jupyter.nu
source /home/ton/.config/nushell/externals/languagetool.nu
source /home/ton/.config/nushell/externals/local-ai.nu
source /home/ton/.config/nushell/externals/ollama.nu
source /home/ton/.config/nushell/externals/ping.nu
source /home/ton/.config/nushell/externals/rust.nu
source /home/ton/.config/nushell/externals/vega-lite.nu
source /home/ton/.config/nushell/scripts/git-remote-storage.nu
source /home/ton/.config/nushell/scripts/gitgud.nu
source /home/ton/.config/nushell/scripts/system-helpers.nu
