---
- name: Link the Kitty Nord theme
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/kitty/theme.conf"
    dest:  ~/.config/kitty/theme.conf
    state: link

- name: Link the Kitty config
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/kitty/kitty.conf"
    dest:  ~/.config/kitty/kitty.conf
    state: link

- name: Link the Chrome Dev flags
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/chrome-flags.conf"
    dest: ~/.config/chrome-dev-flags.conf
    state: link

- name: Link the Chrome flags
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/chrome-flags.conf"
    dest: ~/.config/chrome-flags.conf
    state: link

- name: Link the Chromium flags
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/chrome-flags.conf"
    dest: ~/.config/chromium-flags.conf
    state: link

- name: Link the Ranger configs
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/ranger/rc.conf"
    dest: ~/.config/ranger/rc.conf
    state: link

- name: Install Ranger Icons
  tags: dotconfigs
  git:
    repo: git@github.com:alexanderjeurissen/ranger_devicons.git
    dest: ~/.config/ranger/plugins/ranger_devicons

- name: Link the emoji font config
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/fontconfig/99-noto-color-emoji.conf"
    dest: ~/.config/fontconfig/conf.d/99-noto-color-emoji.conf
    state: link

- name: Link the Espanso config
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/espanso/default.yaml"
    dest:  ~/.config/espanso/default.yml
    state: link

- name: Link the Cheat config
  tags: dotconfigs
  file:
    src: "{{ role_path }}/files/dot_config/cheat"
    dest:  ~/.config/cheat/cheatsheets/personal
    state: link
