# Extra autostart processes
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swaync
exec-once = uwsm app -- wl-clip-persist --clipboard regular
exec-once = uwsm app -- copyq --start-server
exec-once = uwsm app -- vicinae server
exec-once = uwsm app -- kdeconnect-indicator
