# Extra env variables
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = XDG_MENU_PREFIX,arch-
env = GTK_USE_PORTAL,1
env = GDK_DEBUG,portals

# Force Java to use the Wayland toolkit
# env = _JAVA_OPTIONS,-Dawt.toolkit.name=WLToolkit

env = BROWSER,junction

# Some games only lauch if they think they are in a SteamDeck (looking at you Sony/Playstation...)
env = SteamDeck,1
