# Float calculators
windowrule {
  name = Qalculate float
  float = on
  pin = on
  match:class = (io.github.Qalculate.qalculate-qt|qalculate-gtk)
}


# Rule for floating windows
windowrule {
  name = Junction float
  float = on
  match:class = re.sonny.Junction
}

windowrule {
  name = File picker float
  float = on
  match:initial_title = (Open File)
}

windowrule {
  name = Calendar float
  float = on
  match:class = (org.gnome.Calendar)
}


windowrule {
  name = KDE portal float
  float = on
  size = (monitor_w*0.5) 720
  match:initial_class = org.freedesktop.impl.portal.desktop.kde
}


windowrule {
  name = KDE Connect float
  float = on
  size = 950 670
  match:class = org.kde.kdeconnect.app
}


windowrule {
  name = Thunderbird reminders float
  float = on
  size = 780 320
  pin = on
  match:class = org.mozilla.Thunderbird
  match:initial_title = (Calendar Reminders)
}

windowrule {
  name = KoboldCpp Floating
  float = on
  center = on
  match:title = KoboldCpp.*
}

windowrule {
  name = KoboldCpp Tooltips
  float = on
  no_initial_focus = on
  match:title = CTkToplevel
}

# Floating audio mixer
windowrule {
  name = Wiremix float
  float = on
  pin = on
  size = (monitor_w*0.5) (monitor_h*0.5)
  move = ((monitor_w*1)-window_w-8) (32)
  match:class = wiremix.tui
}

windowrule {
  name = Copyq Float
  float = on
  pin = on
  center = on
  size = (monitor_w*0.3) (monitor_h*0.5)
  match:initial_class = com.github.hluk.copyq
}

# Try to correct the floating 1Password Quick Access
windowrule {
  name = 1Password float
  float = on
  pin = on
  match:initial_title = (.*1Password.*)
}

windowrule {
  name = Float OnlyOffice dialog
  float = on
  center = on
  match:initial_class = DesktopEditors
}

# Let Jetbrains popups not lose focus
# windowrule = unset, noinitialfocus, class:(^jetbrains\-.*), initialTitle:(^$), floating:1
# windowrule = focusonactivate on, class:(^jetbrains\-.*), initialTitle:(^$), floating:1
# windowrule = unset, nofocus, class:(^jetbrains\-.*), initialTitle:(^$), floating:1
# windowrule = stayfocused, class:(^jetbrains\-.*), initialTitle:(^$), floating:1

# Floating clipboard manager
# windowrule = float, class:com.github.hluk.copyq
# windowrule = center, class:com.github.hluk.copyq
# windowrule = size 15% 50%, class:com.github.hluk.copyq

# Calendar "widget"
# windowrule = pin, class:(org.gnome.Calendar)
# windowrule = size 360 600, class:(org.gnome.Calendar)
# windowrule = move 50%-w-8 32, class:(org.gnome.Calendar)

# Float additional windows (dialogs) created by scanning software
windowrule {
  name = NAPS2 float
  float = on
  match:class = naps2
  match:initial_title = negative:(^NAPS2.*)
}


# Vicinae rules
layerrule {
  name = Vicinae layer rule
  blur = on
  ignore_alpha = 0
  no_anim = on
  match:namespace = vicinae
}


# Pomodoro
windowrule {
  name = Pomodoro styling
  float = on
  pin = on
  size = 400 532
  match:class = pomodorolm
}


# No window dimming
windowrule {
  name = Discord popout no dimming
  no_dim = on
  match:initial_title = (Discord Popout)
}


# No transparency on media windows
windowrule {
  name = No transparency
  opacity = 1 1
  no_dim = on
  match:class = ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer|vesktop)$
}


bezier = overshoot, 0.05, 0.9, 0.1, 1.1
animation = specialWorkspace, 1, 5, overshoot, slidefadevert -100%

