# Prevent screenshare for sensitive windows
windowrule {
  name = 1Password private
  tag = +private
  match:class = (.*1[Pp]assword.*)
}

windowrule {
  name = Claude private
  tag = +private
  match:class = (Claude)
}

windowrule {
  name = Telegram private
  tag = +private
  match:class = (org.telegram.desktop)
}

windowrule {
  name = Whatsapp private
  tag = +private
  match:class = (.*whatsapp.*)
}

windowrule {
  name = Polkit auth private
  tag = +private
  match:class = polkit-gnome-authentication-agent-1
}


windowrule {
  name = Google Meet private
  tag = +private
  match:title = (^Meet:.*)
}

windowrule {
  name = Slack
  tag = +private
  # match:initialTitle = (Blank Page - Vivaldi)
  match:title = (.* Slack .*)
}

windowrule {
  name = MS Teams private
  tag = +private
  match:title = (.*Microsoft Teams.*)
}

windowrule {
  name = Google Chat private
  tag = +private
  match:title = (.*Chat - .*)
}

windowrule {
  name = Thunderbird private
  tag = +private
  match:class = (org.mozilla.Thunderbird)
}


windowrule {
  name = Comms private
  tag = +private
  match:workspace = special:communication
}

windowrule {
  name = Neoscratchpad private
  tag = +private
  match:workspace = special:neoscratchpad
}


# Apply styling
windowrule {
  name = No screenshare for Private windows
  no_screen_share = 1
  border_color = rgba(E6E6FAFF) rgba(FFA500FF) 45deg
  border_size = 2
  match:tag = private
}


# Toggle noscreenshare
windowrule {
  name = Unprivate
  no_screen_share = 0
  border_color = rgba(E6E6FAFF) rgba(B11226FF) 45deg
  border_size = 2
  match:tag = unprivate
}


bindd = SUPER CTRL ALT SHIFT, H, Toggle window hiding, tagwindow, unprivate

