general {
  gaps_in = 2
  gaps_out = 3
  border_size = 1

  col.active_border = rgba(E6E6FAFF)
  col.inactive_border = rgba(D3D3FFFF)

  resize_on_border = true

  layout = dwindle
}

decoration {
  rounding = 12

  active_opacity = 1.0
  inactive_opacity = 0.7
  dim_inactive = true
  dim_strength = 0.15
  dim_modal = true
  dim_special = 0.3

  shadow {
      enabled = true
      range = 30
      render_power = 5
      offset = 0 5
      color = rgba(00000070)
  }

  blur {
    new_optimizations = true
    xray = true
    special = true
    popups = false
    input_methods = false
  }
}

group {
  drag_into_group = 2
  col.border_active = rgba(815AC0FF)
  col.border_inactive = rgba(C19EE0FF)
  col.border_locked_active = rgba(815AC0FF) rgba(FF930AFF) 45deg
  col.border_locked_inactive = rgba(C19EE0FF) rgba(FF930AFF) 45deg

  groupbar {
    enabled = true
    gradients = true
    height = 12

    font_size = 10
    font_weight_active = ultraheavy
    font_weight_inactive = normal
    text_color = rgba(B4BEFEFF)
    text_color_inactive = rgba(FFFFFFFF)

    rounding = 8
    gradient_rounding = 8
    gradient_rounding_power = 4.0

    gaps_in = 2
    gaps_out = 1
    indicator_gap = 1

    col.active = rgba(1E1E2EFF)
    col.inactive = rgba(11111B99)

    col.locked_active = rgba(1E1E2EFF) rgba(FF930AFF) 45deg
    col.locked_inactive = rgba(11111BFF) rgba(FF930AFF) 45deg
  }
}

misc {
  focus_on_activate = true
}

# DankMaterialShell
layerrule {
  name = DMS layer rule
  no_anim = on
  match:namespace = ^(dms)$
}


# Open DMS windows as floating by default
windowrule {
  name = QuickShell float
  float = on
  match:class = ^(org.quickshell)$
}


