# Workspaces for the main monitor
workspace = 1, monitor:DP-2, persistent:true, default:true
workspace = 2, monitor:DP-2, persistent:true
workspace = 3, monitor:DP-2, persistent:true
workspace = 4, monitor:DP-2, persistent:true
workspace = 5, monitor:DP-2, persistent:true
workspace = 6, monitor:DP-2, persistent:true
workspace = 7, monitor:DP-2, persistent:true
workspace = 8, monitor:DP-2, persistent:true
workspace = 9, monitor:DP-2, persistent:true

# Default workspaces for the other two monitors
workspace = 20, defaultName:tall, monitor:HDMI-A-1, persistent:true, default:true
workspace = 21, defaultName:drawing, monitor:HDMI-A-2, persistent:true, default:true

# The "quake workspace" should alwyas have a terminal open
workspace = special:quake, on-created-empty:ghostty --class=quake.term

# Make communication apps always open on a special workspace
windowrule {
  name = windowrule-1
  workspace = special:communication
  match:class = (.*whatsapp.com.*)
}

windowrule {
  name = windowrule-2
  workspace = special:communication
  match:class = (org.telegram.desktop)
}


# Bindings
unbind = SUPER SHIFT, S
unbind = SUPER, S
bindd = SUPER SHIFT, S, Move to scratchpad, movetoworkspace, special:scratchpad
bindd = SUPER, S, Toggle scratchpad, togglespecialworkspace, scratchpad

bindd = SUPER SHIFT, H, Move to second scratchpad, movetoworkspace, special:neoscratchpad
bindd = SUPER, H, Toggle second scratchpad, togglespecialworkspace, neoscratchpad

# Communication workspace
bindd = SUPER SHIFT, grave, Move to communication workspace, movetoworkspace, special:communication
bindd = SUPER, grave, Toggle communication workspace, togglespecialworkspace, communication

