---
- name: Download .NET installer
  tags: dotnet
  get_url:
    url: https://dot.net/v1/dotnet-install.sh
    dest: ~/.local/bin/dotnet-install
    mode: 774

- name: Verify if .NET is installed
  tags: dotnet
  stat:
    path: /usr/bin/dotnet
  register: is_dotnet_installed
  changed_when: false

- name: Install .NET
  tags: dotnet
  command: dotnet-install
  when: "is_dotnet_installed.stat.exists == False"

- name: Verify installed .NET extensions
  tags: dotnet
  shell: "dotnet tool list -g | tail -n +3 | cut -d ' ' -f 1"
  register: installed_dotnet_extensions
  changed_when: false

- name: Install .NET tools
  tags: dotnet
  command: "dotnet tool install -g {{ item }}"
  loop: "{{ dotnet_tools }}"
  when: "item not in installed_dotnet_extensions.stdout_lines"
