# MPV Configuration File

profile=gpu-hq # High Quality GPU based rendering
vo=gpu-next # Vulkan-based Video Output backend
gpu-api=vulkan # Forces Vulkan instead of OpenGL
gpu-context=waylandvk # Combines Vulkan with Wayland optmizations
hwdec=yes # Enable hardware decoding
autofit-larger=100%x100% # Don't allow new windows to be larger than the screen
