# Added by Toolbox App
PATH="$PATH:/home/ton/.local/share/JetBrains/Toolbox/scripts"

# Use the correct file picker
GTK_USE_PORTAL=1

# Set some variables so webkit apps don't crash when opening
GDK_BACKEND=wayland
WEBKIT_DISABLE_COMPOSITING_MODE=1

# Enable Anti Aliasing for fonts inside Java GUI aplications
_JAVA_OPTIONS='-Dswing.aatext=TRUE -Dawt.useSystemAAFontSettings=on'

# Make electron application behave when in Wayland
ELECTRON_OZONE_PLATFORM_HINT=wayland

# Set some default programs
BROWSER=re.sonny.Junction
EDITOR=nvim
